# Generated by Django 3.2.12 on 2023-01-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'Nuevo'), ('D', 'Destacado'), ('P', 'Promoción')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(max_length=10, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Nombre Completo'),
        ),
    ]
