# Generated by Django 3.2.12 on 2023-01-10 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercadopago_payment', '0002_auto_20230109_2209'),
        ('main_app', '0003_auto_20230109_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name': 'Direccione'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Cupone'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id'], 'verbose_name': 'Producto'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Carrito'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name': 'Renuncia'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfile'},
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.billingaddress', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.coupon', verbose_name='Cupón'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado en:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='on_the_road',
            field=models.BooleanField(default=False, verbose_name='En Distribución'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mercadopago', to='mercadopago_payment.payment', verbose_name='FormaPago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_accepted',
            field=models.BooleanField(default=False, verbose_name='Renuncia Aceptada'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(default=False, verbose_name='Renuncia Solicitada'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Iniciado en:'),
        ),
    ]
