# Generated by Django 3.2.12 on 2023-02-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20230109_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['description'], 'verbose_name': 'Producto'},
        ),
    ]
